#bash computeSBFL.sh Cli 1
#bash computeSBFL.sh Cli 2
#bash computeSBFL.sh Cli 3
#bash computeSBFL.sh Cli 4
#bash computeSBFL.sh Cli 5
#bash computeSBFL.sh Cli 7
#bash computeSBFL.sh Cli 8
#bash computeSBFL.sh Cli 9
#bash computeSBFL.sh Cli 10
#bash computeSBFL.sh Cli 11
#bash computeSBFL.sh Cli 12
bash computeSBFL.sh Cli 13
bash computeSBFL.sh Cli 14
bash computeSBFL.sh Cli 15
bash computeSBFL.sh Cli 16
bash computeSBFL.sh Cli 17
bash computeSBFL.sh Cli 18
bash computeSBFL.sh Cli 19
bash computeSBFL.sh Cli 20
bash computeSBFL.sh Cli 21
bash computeSBFL.sh Cli 22
bash computeSBFL.sh Cli 23
bash computeSBFL.sh Cli 24
bash computeSBFL.sh Cli 25
bash computeSBFL.sh Cli 26
bash computeSBFL.sh Cli 27
bash computeSBFL.sh Cli 28
bash computeSBFL.sh Cli 29
bash computeSBFL.sh Cli 30
bash computeSBFL.sh Cli 31
bash computeSBFL.sh Cli 32
bash computeSBFL.sh Cli 33
bash computeSBFL.sh Cli 34
bash computeSBFL.sh Cli 35
bash computeSBFL.sh Cli 36
bash computeSBFL.sh Cli 37
bash computeSBFL.sh Cli 38
bash computeSBFL.sh Cli 39
bash computeSBFL.sh Cli 40
