bash computeSBFL.sh JacksonCore 1
bash computeSBFL.sh JacksonCore 2
bash computeSBFL.sh JacksonCore 3
bash computeSBFL.sh JacksonCore 4
bash computeSBFL.sh JacksonCore 5
bash computeSBFL.sh JacksonCore 6
bash computeSBFL.sh JacksonCore 7
bash computeSBFL.sh JacksonCore 8
bash computeSBFL.sh JacksonCore 9
bash computeSBFL.sh JacksonCore 10
bash computeSBFL.sh JacksonCore 11
bash computeSBFL.sh JacksonCore 12
bash computeSBFL.sh JacksonCore 13
bash computeSBFL.sh JacksonCore 14
bash computeSBFL.sh JacksonCore 15
bash computeSBFL.sh JacksonCore 16
bash computeSBFL.sh JacksonCore 17
bash computeSBFL.sh JacksonCore 18
bash computeSBFL.sh JacksonCore 19
bash computeSBFL.sh JacksonCore 20
bash computeSBFL.sh JacksonCore 21
bash computeSBFL.sh JacksonCore 22
bash computeSBFL.sh JacksonCore 23
bash computeSBFL.sh JacksonCore 24
bash computeSBFL.sh JacksonCore 25
bash computeSBFL.sh JacksonCore 26
