bash computeSBFL.sh Codec 1
bash computeSBFL.sh Codec 2
bash computeSBFL.sh Codec 3
bash computeSBFL.sh Codec 4
bash computeSBFL.sh Codec 5
bash computeSBFL.sh Codec 6
bash computeSBFL.sh Codec 7
bash computeSBFL.sh Codec 8
bash computeSBFL.sh Codec 9
bash computeSBFL.sh Codec 10
bash computeSBFL.sh Codec 11
bash computeSBFL.sh Codec 12
bash computeSBFL.sh Codec 13
bash computeSBFL.sh Codec 14
bash computeSBFL.sh Codec 15
bash computeSBFL.sh Codec 16
bash computeSBFL.sh Codec 17
bash computeSBFL.sh Codec 18
