bash computeSBFL.sh Math 1
bash computeSBFL.sh Math 2
bash computeSBFL.sh Math 3
bash computeSBFL.sh Math 4
bash computeSBFL.sh Math 5
bash computeSBFL.sh Math 6
bash computeSBFL.sh Math 7
bash computeSBFL.sh Math 8
bash computeSBFL.sh Math 9
bash computeSBFL.sh Math 10
bash computeSBFL.sh Math 11
bash computeSBFL.sh Math 12
bash computeSBFL.sh Math 13
bash computeSBFL.sh Math 14
bash computeSBFL.sh Math 15
bash computeSBFL.sh Math 16
bash computeSBFL.sh Math 17
bash computeSBFL.sh Math 18
bash computeSBFL.sh Math 19
bash computeSBFL.sh Math 20
bash computeSBFL.sh Math 21
bash computeSBFL.sh Math 22
bash computeSBFL.sh Math 23
bash computeSBFL.sh Math 24
bash computeSBFL.sh Math 25
bash computeSBFL.sh Math 26
bash computeSBFL.sh Math 27
bash computeSBFL.sh Math 28
bash computeSBFL.sh Math 29
bash computeSBFL.sh Math 30
bash computeSBFL.sh Math 31
bash computeSBFL.sh Math 32
bash computeSBFL.sh Math 33
bash computeSBFL.sh Math 34
bash computeSBFL.sh Math 35
bash computeSBFL.sh Math 36
bash computeSBFL.sh Math 37
bash computeSBFL.sh Math 38
bash computeSBFL.sh Math 39
bash computeSBFL.sh Math 40
bash computeSBFL.sh Math 41
bash computeSBFL.sh Math 42
bash computeSBFL.sh Math 43
bash computeSBFL.sh Math 44
bash computeSBFL.sh Math 45
bash computeSBFL.sh Math 46
bash computeSBFL.sh Math 47
bash computeSBFL.sh Math 48
bash computeSBFL.sh Math 49
bash computeSBFL.sh Math 50
bash computeSBFL.sh Math 51
bash computeSBFL.sh Math 52
bash computeSBFL.sh Math 53
bash computeSBFL.sh Math 54
bash computeSBFL.sh Math 55
bash computeSBFL.sh Math 56
bash computeSBFL.sh Math 57
bash computeSBFL.sh Math 58
bash computeSBFL.sh Math 59
bash computeSBFL.sh Math 60
bash computeSBFL.sh Math 61
bash computeSBFL.sh Math 62
bash computeSBFL.sh Math 63
bash computeSBFL.sh Math 64
bash computeSBFL.sh Math 65
bash computeSBFL.sh Math 66
bash computeSBFL.sh Math 67
bash computeSBFL.sh Math 68
bash computeSBFL.sh Math 69
bash computeSBFL.sh Math 70
bash computeSBFL.sh Math 71
bash computeSBFL.sh Math 72
bash computeSBFL.sh Math 73
bash computeSBFL.sh Math 74
bash computeSBFL.sh Math 75
bash computeSBFL.sh Math 76
bash computeSBFL.sh Math 77
bash computeSBFL.sh Math 78
bash computeSBFL.sh Math 79
bash computeSBFL.sh Math 80
bash computeSBFL.sh Math 81
bash computeSBFL.sh Math 82
bash computeSBFL.sh Math 83
bash computeSBFL.sh Math 84
bash computeSBFL.sh Math 85
bash computeSBFL.sh Math 86
bash computeSBFL.sh Math 87
bash computeSBFL.sh Math 88
bash computeSBFL.sh Math 89
bash computeSBFL.sh Math 90
bash computeSBFL.sh Math 91
bash computeSBFL.sh Math 92
bash computeSBFL.sh Math 93
bash computeSBFL.sh Math 94
bash computeSBFL.sh Math 95
bash computeSBFL.sh Math 96
bash computeSBFL.sh Math 97
bash computeSBFL.sh Math 98
bash computeSBFL.sh Math 99
bash computeSBFL.sh Math 100
bash computeSBFL.sh Math 101
bash computeSBFL.sh Math 102
bash computeSBFL.sh Math 103
bash computeSBFL.sh Math 104
bash computeSBFL.sh Math 105
bash computeSBFL.sh Math 106
