bash computeSBFL.sh Csv 1
bash computeSBFL.sh Csv 2
bash computeSBFL.sh Csv 3
bash computeSBFL.sh Csv 4
bash computeSBFL.sh Csv 5
bash computeSBFL.sh Csv 6
bash computeSBFL.sh Csv 7
bash computeSBFL.sh Csv 8
bash computeSBFL.sh Csv 9
bash computeSBFL.sh Csv 10
bash computeSBFL.sh Csv 11
bash computeSBFL.sh Csv 12
bash computeSBFL.sh Csv 13
bash computeSBFL.sh Csv 14
bash computeSBFL.sh Csv 15
bash computeSBFL.sh Csv 16
