bash computeSBFL.sh JxPath 1
bash computeSBFL.sh JxPath 2
bash computeSBFL.sh JxPath 3
bash computeSBFL.sh JxPath 4
bash computeSBFL.sh JxPath 5
bash computeSBFL.sh JxPath 6
bash computeSBFL.sh JxPath 7
bash computeSBFL.sh JxPath 8
bash computeSBFL.sh JxPath 9
bash computeSBFL.sh JxPath 10
bash computeSBFL.sh JxPath 11
bash computeSBFL.sh JxPath 12
bash computeSBFL.sh JxPath 13
bash computeSBFL.sh JxPath 14
bash computeSBFL.sh JxPath 15
bash computeSBFL.sh JxPath 16
bash computeSBFL.sh JxPath 17
bash computeSBFL.sh JxPath 18
bash computeSBFL.sh JxPath 19
bash computeSBFL.sh JxPath 20
bash computeSBFL.sh JxPath 21
bash computeSBFL.sh JxPath 22
