bash computeSBFL.sh Time 1
bash computeSBFL.sh Time 2
bash computeSBFL.sh Time 3
bash computeSBFL.sh Time 4
bash computeSBFL.sh Time 5
bash computeSBFL.sh Time 6
bash computeSBFL.sh Time 7
bash computeSBFL.sh Time 8
bash computeSBFL.sh Time 9
bash computeSBFL.sh Time 10
bash computeSBFL.sh Time 11
bash computeSBFL.sh Time 12
bash computeSBFL.sh Time 13
bash computeSBFL.sh Time 14
bash computeSBFL.sh Time 15
bash computeSBFL.sh Time 16
bash computeSBFL.sh Time 17
bash computeSBFL.sh Time 18
bash computeSBFL.sh Time 19
bash computeSBFL.sh Time 20
bash computeSBFL.sh Time 22
bash computeSBFL.sh Time 23
bash computeSBFL.sh Time 24
bash computeSBFL.sh Time 25
bash computeSBFL.sh Time 26
bash computeSBFL.sh Time 27
