#bash computeSBFL.sh Closure 3
#bash computeSBFL.sh Closure 4
#bash computeSBFL.sh Closure 5
#bash computeSBFL.sh Closure 6
#bash computeSBFL.sh Closure 7
#bash computeSBFL.sh Closure 8
#bash computeSBFL.sh Closure 9
#bash computeSBFL.sh Closure 10
#bash computeSBFL.sh Closure 11
#bash computeSBFL.sh Closure 12
#bash computeSBFL.sh Closure 13
#bash computeSBFL.sh Closure 14
#bash computeSBFL.sh Closure 15
#bash computeSBFL.sh Closure 16
#bash computeSBFL.sh Closure 17
#bash computeSBFL.sh Closure 18
#bash computeSBFL.sh Closure 19
#bash computeSBFL.sh Closure 20
#bash computeSBFL.sh Closure 21
#bash computeSBFL.sh Closure 22
#bash computeSBFL.sh Closure 23
#bash computeSBFL.sh Closure 24
#bash computeSBFL.sh Closure 25
#bash computeSBFL.sh Closure 26
#bash computeSBFL.sh Closure 27
#bash computeSBFL.sh Closure 28
#bash computeSBFL.sh Closure 29
#bash computeSBFL.sh Closure 30
#bash computeSBFL.sh Closure 31
#bash computeSBFL.sh Closure 32
#bash computeSBFL.sh Closure 33
#bash computeSBFL.sh Closure 34
#bash computeSBFL.sh Closure 35
#bash computeSBFL.sh Closure 36
#bash computeSBFL.sh Closure 37
#bash computeSBFL.sh Closure 38
#bash computeSBFL.sh Closure 39
#bash computeSBFL.sh Closure 40
#bash computeSBFL.sh Closure 41
#bash computeSBFL.sh Closure 42
#bash computeSBFL.sh Closure 43
#bash computeSBFL.sh Closure 44
#bash computeSBFL.sh Closure 45
#bash computeSBFL.sh Closure 46
#bash computeSBFL.sh Closure 47
#bash computeSBFL.sh Closure 48
#bash computeSBFL.sh Closure 49
#bash computeSBFL.sh Closure 50
#bash computeSBFL.sh Closure 51
#bash computeSBFL.sh Closure 52
#bash computeSBFL.sh Closure 53
#bash computeSBFL.sh Closure 54
#bash computeSBFL.sh Closure 55
#bash computeSBFL.sh Closure 56
#bash computeSBFL.sh Closure 57
#bash computeSBFL.sh Closure 58
#bash computeSBFL.sh Closure 59
#bash computeSBFL.sh Closure 60
#bash computeSBFL.sh Closure 61
#bash computeSBFL.sh Closure 62
#bash computeSBFL.sh Closure 64
#bash computeSBFL.sh Closure 65
#bash computeSBFL.sh Closure 66
#bash computeSBFL.sh Closure 67
#bash computeSBFL.sh Closure 68
#bash computeSBFL.sh Closure 69
#bash computeSBFL.sh Closure 70
#bash computeSBFL.sh Closure 71
#bash computeSBFL.sh Closure 72
#bash computeSBFL.sh Closure 73
#bash computeSBFL.sh Closure 74
#bash computeSBFL.sh Closure 75
#bash computeSBFL.sh Closure 76
#bash computeSBFL.sh Closure 77
#bash computeSBFL.sh Closure 78
#bash computeSBFL.sh Closure 79
#bash computeSBFL.sh Closure 80
#bash computeSBFL.sh Closure 81
#bash computeSBFL.sh Closure 82
#bash computeSBFL.sh Closure 83
#bash computeSBFL.sh Closure 84
#bash computeSBFL.sh Closure 85
#bash computeSBFL.sh Closure 86
#bash computeSBFL.sh Closure 87
#bash computeSBFL.sh Closure 88
#bash computeSBFL.sh Closure 89
#bash computeSBFL.sh Closure 90
#bash computeSBFL.sh Closure 91
#bash computeSBFL.sh Closure 92
#bash computeSBFL.sh Closure 94
#bash computeSBFL.sh Closure 95
#bash computeSBFL.sh Closure 96
#bash computeSBFL.sh Closure 97
#bash computeSBFL.sh Closure 98
#bash computeSBFL.sh Closure 99
#bash computeSBFL.sh Closure 100
#bash computeSBFL.sh Closure 101
#bash computeSBFL.sh Closure 102
#bash computeSBFL.sh Closure 103
#bash computeSBFL.sh Closure 104
#bash computeSBFL.sh Closure 105
#bash computeSBFL.sh Closure 106
#bash computeSBFL.sh Closure 107
#bash computeSBFL.sh Closure 108
#bash computeSBFL.sh Closure 109
#bash computeSBFL.sh Closure 110
#bash computeSBFL.sh Closure 111
#bash computeSBFL.sh Closure 112
#bash computeSBFL.sh Closure 113
#bash computeSBFL.sh Closure 114
#bash computeSBFL.sh Closure 115
#bash computeSBFL.sh Closure 116
#bash computeSBFL.sh Closure 117
#bash computeSBFL.sh Closure 118
#bash computeSBFL.sh Closure 119
#bash computeSBFL.sh Closure 120
#bash computeSBFL.sh Closure 121
#bash computeSBFL.sh Closure 122
bash computeSBFL.sh Closure 123
bash computeSBFL.sh Closure 124
bash computeSBFL.sh Closure 125
bash computeSBFL.sh Closure 126
bash computeSBFL.sh Closure 127
bash computeSBFL.sh Closure 128
bash computeSBFL.sh Closure 129
bash computeSBFL.sh Closure 130
bash computeSBFL.sh Closure 131
bash computeSBFL.sh Closure 132
bash computeSBFL.sh Closure 133
