bash computeSBFL.sh Lang 1
bash computeSBFL.sh Lang 2
bash computeSBFL.sh Lang 3
bash computeSBFL.sh Lang 4
bash computeSBFL.sh Lang 5
bash computeSBFL.sh Lang 6
bash computeSBFL.sh Lang 7
bash computeSBFL.sh Lang 8
bash computeSBFL.sh Lang 9
bash computeSBFL.sh Lang 10
bash computeSBFL.sh Lang 11
bash computeSBFL.sh Lang 12
bash computeSBFL.sh Lang 13
bash computeSBFL.sh Lang 14
bash computeSBFL.sh Lang 15
bash computeSBFL.sh Lang 16
bash computeSBFL.sh Lang 17
bash computeSBFL.sh Lang 18
bash computeSBFL.sh Lang 19
bash computeSBFL.sh Lang 20
bash computeSBFL.sh Lang 21
bash computeSBFL.sh Lang 22
bash computeSBFL.sh Lang 23
bash computeSBFL.sh Lang 24
bash computeSBFL.sh Lang 25
bash computeSBFL.sh Lang 26
bash computeSBFL.sh Lang 27
bash computeSBFL.sh Lang 28
bash computeSBFL.sh Lang 29
bash computeSBFL.sh Lang 30
bash computeSBFL.sh Lang 31
bash computeSBFL.sh Lang 32
bash computeSBFL.sh Lang 33
bash computeSBFL.sh Lang 34
bash computeSBFL.sh Lang 35
bash computeSBFL.sh Lang 36
bash computeSBFL.sh Lang 37
bash computeSBFL.sh Lang 38
bash computeSBFL.sh Lang 39
bash computeSBFL.sh Lang 40
bash computeSBFL.sh Lang 41
bash computeSBFL.sh Lang 42
bash computeSBFL.sh Lang 43
bash computeSBFL.sh Lang 44
bash computeSBFL.sh Lang 45
bash computeSBFL.sh Lang 46
bash computeSBFL.sh Lang 47
bash computeSBFL.sh Lang 48
bash computeSBFL.sh Lang 49
bash computeSBFL.sh Lang 50
bash computeSBFL.sh Lang 51
bash computeSBFL.sh Lang 52
bash computeSBFL.sh Lang 53
bash computeSBFL.sh Lang 54
bash computeSBFL.sh Lang 55
bash computeSBFL.sh Lang 56
bash computeSBFL.sh Lang 57
bash computeSBFL.sh Lang 58
bash computeSBFL.sh Lang 59
bash computeSBFL.sh Lang 60
bash computeSBFL.sh Lang 61
bash computeSBFL.sh Lang 62
bash computeSBFL.sh Lang 63
bash computeSBFL.sh Lang 64
bash computeSBFL.sh Lang 65
