bash computeSBFL.sh Compress 1
bash computeSBFL.sh Compress 2
bash computeSBFL.sh Compress 3
bash computeSBFL.sh Compress 4
bash computeSBFL.sh Compress 5
bash computeSBFL.sh Compress 6
bash computeSBFL.sh Compress 7
bash computeSBFL.sh Compress 8
bash computeSBFL.sh Compress 9
bash computeSBFL.sh Compress 10
bash computeSBFL.sh Compress 11
bash computeSBFL.sh Compress 12
bash computeSBFL.sh Compress 13
bash computeSBFL.sh Compress 14
bash computeSBFL.sh Compress 15
bash computeSBFL.sh Compress 16
bash computeSBFL.sh Compress 17
bash computeSBFL.sh Compress 18
bash computeSBFL.sh Compress 19
bash computeSBFL.sh Compress 20
bash computeSBFL.sh Compress 21
bash computeSBFL.sh Compress 22
bash computeSBFL.sh Compress 23
bash computeSBFL.sh Compress 24
bash computeSBFL.sh Compress 25
bash computeSBFL.sh Compress 26
bash computeSBFL.sh Compress 27
bash computeSBFL.sh Compress 28
bash computeSBFL.sh Compress 29
bash computeSBFL.sh Compress 30
bash computeSBFL.sh Compress 31
bash computeSBFL.sh Compress 32
bash computeSBFL.sh Compress 33
bash computeSBFL.sh Compress 34
bash computeSBFL.sh Compress 35
bash computeSBFL.sh Compress 36
bash computeSBFL.sh Compress 37
bash computeSBFL.sh Compress 38
bash computeSBFL.sh Compress 39
bash computeSBFL.sh Compress 40
bash computeSBFL.sh Compress 41
bash computeSBFL.sh Compress 42
bash computeSBFL.sh Compress 43
bash computeSBFL.sh Compress 44
bash computeSBFL.sh Compress 45
bash computeSBFL.sh Compress 46
bash computeSBFL.sh Compress 47
