bash computeSBFL.sh Gson 1
bash computeSBFL.sh Gson 2
bash computeSBFL.sh Gson 3
bash computeSBFL.sh Gson 4
bash computeSBFL.sh Gson 5
bash computeSBFL.sh Gson 6
bash computeSBFL.sh Gson 7
bash computeSBFL.sh Gson 8
bash computeSBFL.sh Gson 9
bash computeSBFL.sh Gson 10
bash computeSBFL.sh Gson 11
bash computeSBFL.sh Gson 12
bash computeSBFL.sh Gson 13
bash computeSBFL.sh Gson 14
bash computeSBFL.sh Gson 15
bash computeSBFL.sh Gson 16
bash computeSBFL.sh Gson 17
bash computeSBFL.sh Gson 18
